Introduce inspect_level in inspector and metadata
hitsz-ids/synthetic-data-generator pull request #113
Opened 2024-01-17 03:17 UTC by MooooCat

## Description

Inspected level is a concept newly introduced in version 0.1.5. 

Since a single column in the table may be marked by different inspectors at the same time, which may cause confuse.

Thus, a `inspect_level` is introduced when determining the specific type of a column.

## Motivation and Context

A single column, can be labeled by different multiple inspector.

For example, A email column may be recognized as email, but it may also be recognized as the id column, and it may also be recognized by different inspectors at the same time identified as a discrete column, which will cause confusion in subsequent processing. 

Also, you can see from our multi-table demo dataset, child table "train",  the `Date` column is marked twice, as discrete type and date type.

We will preset different inspector levels for different inspectors, usually more specific inspectors will get higher levels, and general inspectors (like discrete) will have inspect_level. In baseclass, the inspect_level is set to 1.

## How has this been tested?

## Types of changes

- [ ] Maintenance (no change in code, maintain the project's CI, docs, etc.)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2024-01-17 08:53 UTC, Wh1isper commented
I suggest limiting the priority to a range such as (1-100), the larger the priority, the sooner the execution. 

Our built-in inspector should be presented in a hierarchy (10,20,30...), so that users can insert a custom inspector from the middle.

2024-01-17 12:32 UTC, Guo-Yunzhe commented
Nice suggestion!

I will plan it later.

從我的iPhone傳送

Zhongsheng Ji ***@***.***>於2024年1月17日 16:53寫道：

﻿

I suggest limiting the priority to a range such as (1-100), the larger the priority, the sooner the execution.

Our built-in inspector should be presented in a hierarchy (10,20,30...), so that users can insert a custom inspector from the middle.

—
Reply to this email directly, view it on GitHub<https://github.com/hitsz-ids/synthetic-data-generator/pull/113#issuecomment-1895358416>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/ADC2LYAXKSC7XNPOMK54QYDYO6GQLAVCNFSM6AAAAABB52NZOSVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTQOJVGM2TQNBRGY>.
You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

2024-01-18 05:43 UTC, Wh1isper requested changes
Request some teses on `inspect_level`

2024-01-19 14:55 UTC, Wh1isper requested changes

2024-01-19 14:55 UTC, Wh1isper commented on sdgx/data_models/metadata.py
> +    column_inspect_level: Dict[str, int] = defaultdict()
Backwards compatibility does not exist for `inspect_level` as `10`.

```suggestion
    column_inspect_level: Dict[str, int] = defaultdict(lambda: 10)
```

2024-01-19 15:02 UTC, MooooCat commented
It seems that all our package build test are failed because the SSL error of datahub.io., causing the fail of some unit test (downloading the demo dataset).

2024-01-19 15:42 UTC, Wh1isper commented
Can a more stable data source be found? Or hitz-ids could provide a public download source similar to s3?

2024-01-20 00:57 UTC, Guo-Yunzhe commented
Kangda Wu will work on this

從我的iPhone傳送

Zhongsheng Ji ***@***.***>於2024年1月19日 23:42寫道：

﻿

Can a more stable data source be found? Or hitz-ids could provide a public download source similar to s3?

2024-01-20 11:17 UTC, Wh1isper approved these changes
LGTM, just one more question, should we add some test in `test_metadata.py` for `column_inspect_level`?

2024-01-20 11:17 UTC, merged

2024-01-20 11:19 UTC, MooooCat commented
> LGTM, just one more question, should we add some tests in `test_metadata.py` for `column_inspect_level`? We can leave it in next PR.

Sure, currently some test are in each inspectors, we can add test cases in `test_metadata.py`