Update Base Class of Metric
hitsz-ids/synthetic-data-generator pull request #60
Opened 2023-12-11 02:14 UTC by MooooCat

## Description

Updated several files in the `sdgx/metric/` directory

## Motivation and Context

Update the metric base class used to evaluate the quality of synthetic data

## How has this been tested?

After the specific metric is implemented, that metric will be integrated into the `test/` directory and tested using pytest.

## Types of changes

- [ ] Maintenance (no change in code, maintain the project's CI, docs, etc.)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2023-12-11 02:18 UTC, Wh1isper requested changes

2023-12-11 02:18 UTC, Wh1isper commented on sdgx/metrics/column/base.py
> +class columnMetric(object):
```suggestion
class ColumnMetric(object):
```

2023-12-11 02:18 UTC, Wh1isper commented on sdgx/metrics/single_table/base.py
> +class singleTableMetric:
```suggestion
class SingleTableMetric:
```

2023-12-11 02:18 UTC, Wh1isper commented on sdgx/metrics/single_table/base.py
> +    def calculate(real_data, synthetic_data):
```suggestion
    def calculate(self, real_data, synthetic_data):
```

2023-12-11 02:25 UTC, Wh1isper commented
Metric isn't the focus at the moment, I'm in favour of us being able to put a demo on it first, but it might not look like this.

2023-12-11 02:31 UTC, Wh1isper commented
When we consider `metrics` as a standalone module, what we expect is basically to input the generated table with the original table. Then `calculate` something like a score or an analysis report. 

But considering that the generated and raw data are **not necessarily** csv files and pandas can't handle very large amounts of data, then we will get a **restricted metrics** class(mostly by performance). Maybe we should separate it to model and data interface.

2023-12-11 06:31 UTC, MooooCat commented
> Metric isn't the focus at the moment, I'm in favour of us being able to put a demo on it first, but it might not look like this.

From an algorithmic perspective, metric can become a standalone module (so as to models). We now need to complete the entire process through adding the metric module.

Currently @sjh120  is implementing Jensen–Shannon Divergence(JSD Feature) and adding it to the demo of single-table data generation example, we can suggest him to merge JSD Feature and new demo into this branch.

2023-12-11 06:36 UTC, Wh1isper commented
> and adding it to the demo of single-table data generation example

Good! It would make sense if this PR could contain working demos.

2023-12-11 06:49 UTC, MooooCat commented
> But considering that the generated and raw data are **not necessarily** csv files and pandas can't handle very large amounts of data, then we will get a **restricted metrics** class(mostly by performance). Maybe we should separate it to model and data interface.


This is indeed an important factor and has been ignored (even by other simulation data projects).

I have a suggestion, please evaluate if it is suitable.

Developers first implement the `calculate` method and demos which can handle non-big data situations (this can be completed this week and next week), then we use new data interfaces to make performance optimization for large-scale data situation.

Maybe the same approach can be used for the our models (Synthesizer).

2023-12-11 06:51 UTC, Wh1isper commented
> Developers first implement the calculate method and demos which can handle non-big data situations (this can be completed this week and next week)

It's ok, I'm glad to see that there are practices that can be referenced, it's much better than imagining things out of thin air.

2023-12-18 08:39 UTC, MooooCat commented
At present, this PR contains:

- three base classes of synthetic data metric;
- one implementation of column metric;
- one example of column metric.

I prefer to merge this PR at this stage.

2023-12-18 08:42 UTC, Wh1isper approved these changes

2023-12-18 08:43 UTC, merged

2023-12-18 09:22 UTC, Wh1isper commented
@all-contributors please add @sjh120  for code